const express = require('express')
const Obito = require('../common/entities/obito')
const Funeraria = require('../common/entities/funeraria')
const ObitoRepository = require('../repositories/ObitoRepository')
const CommentRepository = require('../repositories/CommentRepository')
const CreateObitoCommand = require('../resources/createObito/createObitoCommand')
const FunerariaRepository = require('../repositories/FunerariaRepository')
const CreateObitoController = require('../resources/createObito/createObitoController')
const GetMyFunerariasQuery = require('../resources/getMyFunerarias/getMyFunerariasQuery')
const GetMyObitosController = require('../resources/getMyObitos/getMyObitosController')
const GetMyObitosQuery = require('../resources/getMyObitos/getMyObitosQuery')
const EditObitoCommand = require('../resources/editObito/editObitoCommand')
const EditObitoController = require('../resources/editObito/editObitoController')
const CreateObitoPhotoCommand = require('../resources/createObitoPhoto/createObitoPhotoCommand')
const CreateObitoPhotoController = require('../resources/createObitoPhoto/createObitoPhotoController')
const WriteCommentCommand = require('../resources/writeComment/writeCommentCommand')
const WriteCommentController = require('../resources/writeComment/writeCommentController')
const GetObitosCommentsQuery = require('../resources/getObitosComments/getObitosCommentsQuery')
const GetObitosCommentsController = require('../resources/getObitosComments/getObitosCommentsController')
const EditCommentCommand = require('../resources/editComment/editCommentCommand')
const EditCommentController = require('../resources/editComment/editCommentController')
const DeleteCommentCommand = require('../resources/deleteComment/deleteCommentCommand')
const DeleteCommentController = require('../resources/deleteComment/deleteCommentController')

require('dotenv').config()

const router = express.Router()
const commentRepository = new CommentRepository(process.env.DATABASE_URL)
const funerariaRepository = new FunerariaRepository(process.env.DATABASE_URL)
const obitoRepository = new ObitoRepository(process.env.DATABASE_URL)
const createObitoCommand = new CreateObitoCommand(obitoRepository)
const createObitoController = new CreateObitoController(createObitoCommand)
const getMyObitosQuery = new GetMyObitosQuery(obitoRepository)
const getMyObitosController = new GetMyObitosController(getMyObitosQuery)
const editObitoCommand = new EditObitoCommand(obitoRepository, funerariaRepository)
const editObitoController = new EditObitoController(editObitoCommand)
const createObitoPhotoCommand = new CreateObitoPhotoCommand(obitoRepository)
const createObitoPhotoController = new CreateObitoPhotoController(createObitoPhotoCommand)
const writeCommentCommand = new WriteCommentCommand(obitoRepository, commentRepository)
const writeCommentController = new WriteCommentController(writeCommentCommand)

const getObitosCommentsQuery = new GetObitosCommentsQuery(obitoRepository, commentRepository)
const getObitosCommentsController = new GetObitosCommentsController(getObitosCommentsQuery)

const editCommentCommand = new EditCommentCommand(commentRepository)
const editCommentController = new EditCommentController(editCommentCommand)

const deleteCommentCommand = new DeleteCommentCommand(commentRepository)
const deleteCommentController = new DeleteCommentController(deleteCommentCommand)

const multerconfig = require('../common/multer-config')
const { validateUser } = require('../middlewares/ValidateUser')

router.post('/', validateUser, createObitoController.execute())
router.post('/comments', validateUser, writeCommentController.execute())
router.put('/comments/:commentid', validateUser, editCommentController.execute())
router.delete('/comments/:commentid', validateUser, deleteCommentController.execute())
router.get("/comments/:obitoid", getObitosCommentsController.execute())
router.get('/:funerariaid', validateUser, getMyObitosController.execute())
router.put('/edit/:obitoid', validateUser, editObitoController.execute())
router.put('/photo/:obitoid', validateUser, multerconfig, createObitoPhotoController.execute())


module.exports = router