const express = require('express')
const { User } = require('../common/entities/user')
const CreateUserCommand = require('../resources/createUser/createUserCommand')
const CreateUserController = require('../resources/createUser/createUserController')
const UpdateUserCommand = require('../resources/editUser/editUserCommand')
const UpdateUserController = require('../resources/editUser/editUserController')
const DeleteUserCommand = require('../resources/deleteUser/deleteUserCommand')
const DeleteUserController = require('../resources/deleteUser/deleteUserController')
const LoginController = require('../resources/login/loginController')
const LoginQuery = require('../resources/login/loginQuery')
const UserRepository = require('../repositories/UserRepository')
const { validateUser } = require('../middlewares/ValidateUser')
require('dotenv').config()

const router = express.Router()

const userRepository = new UserRepository(process.env.DATABASE_URL)
const createUserCommand = new CreateUserCommand(userRepository)
const loginQuery = new LoginQuery(userRepository)
const createUserController = new CreateUserController(createUserCommand)
const loginController = new LoginController(loginQuery)
const updateUserCommand = new UpdateUserCommand(userRepository)
const updateUserController = new UpdateUserController(updateUserCommand)
const deleteUserCommand = new DeleteUserCommand(userRepository)
const deleteUserController = new DeleteUserController(deleteUserCommand)

router.post('/', createUserController.execute())
router.post('/auth', loginController.execute())
router.put('/', validateUser, updateUserController.execute())
router.delete('/:userid', validateUser, deleteUserController.execute())
router.get('/', validateUser, (req, res) => {
    return res.status(200).json(req.user)
})

module.exports = router